### ISSUE TITLE
Gibbs sampler

### ISSUE THREAD

**Issue by pauldwkirk** [pauldwkirk/Stephen#1]
Hi Stephen.  I fixed a few bugs.  Summary below:

- There was a small bug in your `chol_update` function.  I have fixed this simply by making use of the `cholupdate` and `choldowndate` functions in the ramcmc package, which are very efficient.
- There were a few small bugs in your `evidence` function.  In particular, there were a few places where `df` needed to be replaced with `d`, and one or two places where I changed the bracketing.
- You had something like `data <- data[-j]` in your sampler, which meant that `data` just kept getting smaller at each iteration.  I commented this out

The code now runs, but you'll see that there is something strange going on with the `class_table`, which means that the `prob` vector ends up with NaNs in it.  I'll leave it to you to have a go at fixing it!

Also, we should ask Josh to install a copy of Matlab on your computer, so that you can see what you get when you run Yee Whye's code, and check that you get the same things!

**Comment by pauldwkirk** [comment]
Hi Stephen.  The error you were seeing was because q[[1]]$n became zero on the 10-th iteration (i.e. you had emptied one of the clusters), which has to be handled as a special case.  If you look in the notes (notesForSC.pdf), you'll see around Equation 26 that it states that these equations are only valid "if the k-th component is not empty".  I have updated your `evidence` function to handle this special case.

It seemed a bit weird that you were hitting this problem though, because although q[[1]]$n became zero, your class_labels vector indicated that actually there should have been a (non-zero) number of items in q[[1]].  The problem was in the line:
`q[[k]] <- add_item(q[[k]], data[j])`
Since k is always 2 (I think), this meant that you only ever added items to component 2 (and hence component 1 was eventually becoming empty).  I have changed to the following:
`q[[pred]] <- add_item(q[[pred]], data[j])`
I've also added some print statements (for debugging), just to check that q[[1]]$n, q[[2]]$n and class_labels are all consistent.  You will probably want to delete this at some point, once you're convinced everything is working as intended.

**Comment by stcolema** [comment]
Cheers! Thanks PK. Git now all set up correctly too and the parameter sampling is possibly working? I suspect something strange is still happening.

**Comment by stcolema** [comment]
I think the gibbs sampler is now working.
